### ISSUE TITLE
Tripled entries in completion

### ISSUE THREAD

**Issue by tomas0430** [martineausimon/nvim-lilypond-suite#11]
Completion shows triplicats.the same three entries in completion menu. I'm using your completion config. I have no idea how to fix this.

**Comment by martineausimon** [comment]
Yes, it's due to the new update of `uga-rosa/cmp-dictionary`, it is no longer necessary to define the paths to the dictionary files (which are already defined in `nvim-lilypond-suite/ftplugin/lilypond.lua`). the following lines are sufficient:

```lua
{ 
  'uga-rosa/cmp-dictionary',
  config = function() 
    require("cmp_dictionary").switcher({
      filetype = {
        lilypond = {}
      },
    })
  end
},
```

I will correct the wiki this weekend!

**Comment by tomas0430** [comment]
Now it works as intended.Thanks
