### ISSUE TITLE
Configure plugin in windows 

### ISSUE THREAD

**Issue by OnlyZero** [martineausimon/nvim-lilypond-suite#12]
Kind regards! Any recommendation?
To make this wonderful “plugin” work in windows? 

![Imagen PNG](https://user-images.githubusercontent.com/6993742/227234545-5f7d601e-2e41-43fb-b599-161aec11ad60.png)
![Imagen PNG 2](https://user-images.githubusercontent.com/6993742/227234561-4a60b2ee-aca2-4395-a631-2783fa3c5d5b.png)

**Comment by martineausimon** [comment]
Hi!

I just made some big changes to the plugin, and I think (hope!) it can now work with Windows, but I need someone to test it. If it is possible for you to take some time that would be great!

The only difference with Unix systems is the audio player: for Windows it works with `timidity` which you need to install.

You can try with this configuration, but it is the default configuration on Windows:

```lua
{
'martineausimon/nvim-lilypond-suite',
dependencies = 'MunifTanjim/nui.nvim',
config = function()
  require('nvls').setup({
    player = {
      midi_synth = "timidity",
      audio_format = "wav",
    }
  })
end
}
```

Things to try:  

- Compile the file (`:LilyCmp`, default `F5`)
- Open the PDF (`:Viewer`, default `F6`)
- The player (`:LilyPlayer`, default `F3`)
- The "quickplayer": make a visual selection and press `F3`

For the others things, everything is in the wiki!

Thanks a lot !

**Comment by OnlyZero** [comment]
> - Hola.
> 
> Acabo de hacer algunos cambios grandes en el plugin, y creo que (espera) ahora puede funcionar con Windows, pero necesito a alguien para probarlo. Si es posible que te tomes algún tiempo eso sería genial.
> 
> La única diferencia con los sistemas Unix es el reproductor de audio: para Windows funciona con `timidity`que tienes que instalar.
> 
> Puedes probar con esta configuración, pero es la configuración predeterminada en Windows:
> 
> ```lua
> {
>   'martineausimon/nvim-lilypond-suite',
>   dependencies = 'MunifTanjim/nui.nvim',
>   config = function()
>     require('nvls').setup({
>       player = {
>         midi_synth = "timidity",
>         audio_format = "wav",
>       }
>     })
>   end
> }
> ```
> 
> Qué cosas que probar:
> 
>     * Compilar el archivo (`:LilyCmp`, por defecto `F5`)
> 
>     * Abrir el PDF (Abierto el`:Viewer`, por defecto `F6`)
> 
>     * El jugador (`:LilyPlayer`, por defecto `F3`)
> 
>     * El "rápido jugador": hacer una selección visual y prensa `F3`
> 
> 
> Para las otras cosas, todo está en la wiki.
> 
> Muchas gracias.

What great news! I'm going to try it out for next 2024.
