### ISSUE TITLE
Syntax highlighting doesn't work when using lazy.nvim

### ISSUE THREAD

**Issue by kflak** [martineausimon/nvim-lilypond-suite#14]
Hi,

Getting some weirdness here after I migrated from Packer to Lazy...

With this setup I get syntax highlighting (although the English names with flats and sharps are not correctly colored): 
```
    {
        'martineausimon/nvim-lilypond-suite',
        dependencies = 'MunifTanjim/nui.nvim',
        config = function()
        end
    },
```
With this I don't:
```
    {
        'martineausimon/nvim-lilypond-suite',
        dependencies = 'MunifTanjim/nui.nvim',
        config = function()
            require('nvls').setup({})
        end
    },
```

Any idea what might be going on here?

Edit: I also have this autocmd: 
```
api.nvim_create_autocmd({"BufEnter"}, {
    pattern = {"*.ly"},
    command = "setlocal formatoptions-=c formatoptions-=r formatoptions-=o | syntax sync fromstart",
    group = group
})
```

**Comment by martineausimon** [comment]
Hi Kenneth,

Sorry for this issue !

I've just try with this small `init.lua` and everything works as expected :

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"

if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end

vim.opt.rtp:prepend(lazypath)

require('lazy').setup(
  { 
    'martineausimon/nvim-lilypond-suite',
    dependencies = 'MunifTanjim/nui.nvim',
    config = function()
      require('nvls').setup({
      })
    end
  }
)
```

Can you send me a minimal version of your config ?

**Comment by kflak** [comment]
Of course, should have done a test with a minimal config first! Sorry about that. 

The minimal config works as expected indeed! I suppose I'll have to just step through my main config to see which plugins conflict with the syntax highlighting. Will keep you posted.

**Comment by martineausimon** [comment]
I've just test it with this lazy config, and everything works... It should be something else, sorry ! Just to be shure : do you have a curly bracket that includes all the plugins ?

```lua
require('lazy').setup({
  {
      'eddyekofo94/gruvbox-flat.nvim',
      lazy = false,
      priority = 1000,
      config = function()
          vim.cmd([[colorscheme gruvbox-flat]])
      end,
      init = function()
         vim.g.gruvbox_flat_style = "hard"
         vim.g.colors_name="gruvbox-flat"
         vim.g.gruvbox_transparent = true
         vim.g.gruvbox_italic_functions = true
      end
  },
  { 
    'martineausimon/nvim-lilypond-suite',
    dependencies = 'MunifTanjim/nui.nvim',
    config = function()
      require('nvls').setup()
    end
  }
})
```

**Comment by kflak** [comment]
Phew, figured it out! I needed to require my plugins at the _end_ of my init.lua, not the beginning, as I had before...

Thanks a lot for taking the time to help me sort out my understanding of `lazy.nvim`!

Roosna & Flak
Contemporary Dance & Music
https://roosnaflak.com

-------- Original Message --------
