### ISSUE TITLE
[FR] Auto-close player on completion

### ISSUE THREAD

**Issue by kflak** [martineausimon/nvim-lilypond-suite#15]
Hi,

Is there a way to close the player automatically after it has reached the end of the file? I currently have it set up not to loop, so I get an exit code 0 when it finishes. Maybe it's possible to trap this somehow and add a hook to it? I don't know enough about the inner workings of the floating window to take a stab at this....

**Comment by martineausimon** [comment]
Hi !
Sorry for the slow response, I'm a bit busy these days !
It should work now : the player window should close when it finishes playing.

**Comment by kflak** [comment]
Awesome, thank you so much!
