### ISSUE TITLE
Feature Request: Allow the user to specify the pdf viewer they want to use for preview

### ISSUE THREAD

**Issue by t4y** [martineausimon/nvim-lilypond-suite#16]
I like using a more minimal pdf viewer to preview compilation of latex or markdown while having a more full-fledged pdf editor as system default for the pdf file type, and I'm kind of missing this feature in nvim-lilypond-suite.

Otherwise great plugin, thank you for taking the time to make it available!

**Comment by martineausimon** [comment]
Thanks for this suggestion!
