### ISSUE TITLE
Player not working when file path contains space

### ISSUE THREAD

**Issue by jeromepochat** [martineausimon/nvim-lilypond-suite#20]
Hi!
When launching player using `<F3>` with a file containing space in path/name (eg. `$HOME/simple test.ly`), it results as failure:
```
stat: cannot statx '/home/jerome/simple': No such file or directory
stat: cannot statx 'test.midi': No such file or directory
Error executing Lua callback: ...hare/nvim/lazy/nvim-lilypond-suite/lua/nvls/lilypond.lua:37: attempt to compare nil with number
stack traceback:
        ...hare/nvim/lazy/nvim-lilypond-suite/lua/nvls/lilypond.lua:37: in function 'lilyPlayer'
        ...hare/nvim/lazy/nvim-lilypond-suite/ftplugin/lilypond.lua:26: in function <...hare/nvim/lazy/nvim
```
Notice that it's working fine for file without space in path/name (eg. `$HOME/simpletest.ly`).

(environment: ArchLinux)

**Comment by martineausimon** [comment]
Hi, sorry for this issue !

I've made a small change and I think it should work now. Can you confirm that ?

Anyway I'm planning a big code refactor this summer, there are things like file name management that really need to be improved...

**Comment by jeromepochat** [comment]
Perfect! I confirm it works since b25de41635d9d585a4fe2e730874cf74a2288aad
Thanks for quick fix!
