### ISSUE TITLE
PDF viewer is not launcher when file path contains space

### ISSUE THREAD

**Issue by jeromepochat** [martineausimon/nvim-lilypond-suite#22]
Hi!
When launching player using <F6> with a file containing space in path/name (eg. $HOME/simple test.ly), it results as failure:
```
[NVLS] File Cinema Paradiso.pdf doesn't exists
```
Notice that it's working fine for file without space in path/name (eg. $HOME/simpletest.ly).

(environment: ArchLinux)

**Comment by martineausimon** [comment]
Hi!
Sorry for this issue... It should work now!

**Comment by jeromepochat** [comment]
Perfect! Thanks for quick fix.
