### ISSUE TITLE
Fluidsynth doesn't work as a player on latest MacOS

### ISSUE THREAD

**Issue by madskjeldgaard** [martineausimon/nvim-lilypond-suite#26]
Hi! 

Just wanted to say that installing the latest fluid synth from homebrew and using that as a player in lilypond-suite doesn't work currently.

I had to specify `timidity` as the midi_synth to make the functionality work (and also install timidity of course)

```
              midi_synth = "timidity", 
```

**Comment by martineausimon** [comment]
Hi,

Sorry for that !

I think another line is missing in the wiki :
In [Arch](https://wiki.archlinux.org/title/Timidity++#SoundFonts) the default soundfont must be specified in /etc/timidity/timidity.cfg

```bash
soundfont /usr/share/soundfonts/FluidR3_GM.sf2
```

However I don't know how it works on MacOS...
