### ISSUE TITLE
"Guile signaled an error for the expression beginning here"

### ISSUE THREAD

**Issue by mccrmck** [martineausimon/nvim-lilypond-suite#27]
Gradually moving my life over to nvim and my lilypond scores that compile fine in Frescobaldi don't seem to work in nvim...various scores (including small test scores) spit out the same error message:

```
opt/homebrew/Cellar/lilypond/2.24.2/share/lilypond/2.24.2/ly/init.ly|65 col 2| error: Guile signaled an error for the expression beginning here
```

Any idea what this could be? Is it something to do with my version of Guile perhaps?

**Comment by martineausimon** [comment]
Hi,

Sorry for that ! I suppose this message comes from nvim quickfix ? If that is so, it's should be the Lilypond stdout. It means Lilypond is working correctly. Could it be an included file which isn't in your path ?
Could you share a minimal sample from your .ly file ?

**Comment by mccrmck** [comment]
Yes, sorry I wasn't clear - the message is from nvim quickfix! Even something like the following will generate the error message for me:

```
\version "2.24.2"

\score {
  \relative {
    c d e f
  }
}
```
Do I need to point nvim-lilypond-suite to a lilypond (or Guile) folder explicitly, or? I've tried a reinstall, but that doesn't seem to help either...could it be a conflict with another nvim plugin perhaps?

**Comment by martineausimon** [comment]
Thanks ! Can you try to compile directly from the terminal ? `lilypond file.ly` ?
For now the plugin isn't able to point a specific version of lilypond, but I can add this if needed !

**Comment by mccrmck** [comment]
Compiling (the above snippet) in the terminal works without a problem...and the same file also compiles in Frescobaldi, for what it's worth.

No need to add versioning, at least not for my sake! :)

**Comment by martineausimon** [comment]
With default config, `:LilyCmp` command should run exactly :

```bash
lilypond -f pdf -o file file.ly
```

Could there be an error in your nvim config ?
Especially in :

```lua
require('nvls').setup({
  lilypond = {
    options = {
      output = "pdf",
      backend = nil,
      include_dir = nil
    }
  }
})
```

**Comment by martineausimon** [comment]
I think this issue is related : https://lists.gnu.org/archive/html/lilypond-user/2023-06/msg00134.html

And the message from Josh Armenta on the forum :


>Found the issue.
>
>Something, somewhere messed up the Ghostscript         permissions.                                            >
>I ran:
>
>sudo chown -R `whoami` /usr/local/share/doc/ghostscript
>brew link --overwrite ghostscript
>
>Which fixed the issue on the following invocation of   lilypond.                                               >
>Thanks for the —verbose hint!

https://lists.gnu.org/archive/html/lilypond-user/2023-06/msg00138.html

**Comment by mccrmck** [comment]
I reduced my nvim config file to just the block you posted, but the issue persists. 

I also tried Josh Armenta's solution, but my terminal insists that Ghostscript is already linked....and it seems Josh had trouble with compiling from the terminal, which is fine for me...hmmm...

**Comment by martineausimon** [comment]
Is there an error if you compile from terminal with `lilypond -f pdf -o file file.ly` ?

**Comment by martineausimon** [comment]
And let's try directly in neovim with `:!lilypond -f pdf -o output_name %` ?

**Comment by mccrmck** [comment]
Compiling from the terminal worked again, but running from nvim gave the same Guile-related error message. Could it be another nvim plugin that's interfering somehow?

(I really appreciate your help with this btw!!)

**Comment by martineausimon** [comment]
Maybe we can have more infos with `--verbose` flag. Can you send the output of `!lilypond --verbose -f pdf -o output_name %` ?

**Comment by mccrmck** [comment]
It looks like the error occurs here: I can post the entire output if you think it's necessary!
```
...
Preparing Ghostscript command to `/var/folders/71/qfb57y415rq_n65h0720_38w0000gn/T//lilypond-tmp-6950945': mark /OutputFile (./lilypond-tmp-6010361.pdf) /CompatibilityLevel 1.4 /PageSize [595.28 841.89] (pdfwrite) finddevice putdeviceprops pop (pdfwrite) selectdevice newpath fill (/var/folders/71/qfb57y415rq_n65h0720_38w0000gn/T//lilypond-tmp-6010361) (r) file .setsafe run
Invoking `gs -dNODISPLAY -dNOSAFER -dNOPAUSE -dBATCH -dAutoRotatePages=/None -dPrinted=false /var/folders/71/qfb57y415rq_n65h0720_38w0000gn/T//lilypond-tmp-6950945'...

GPL Ghostscript 10.02.0 (2023-09-13)
Copyright (C) 2023 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
Error: /ioerror in --setdevice--
Operand stack:   true
Execution stack:   %interp_exit   .runexec2   --nostringval--   setdevice   --nostringval--   2   %stopped_push   --nostringval--   setdevice   setdevice   false   1   %stopped_push   1944   1   3   %oparray_pop   1943   1   3   %oparray_pop   1928   1   3   %oparray_pop   1801   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   setdevice   --nostringval--   2   %stopped_push   --nostringval--   setdevice   1803   1   3   %oparray_pop   setdevice
Dictionary stack:   --dict:755/1123(ro)(G)--   --dict:0/20(G)--   --dict:85/200(L)--
Current allocation mode is local
Last OS error: Read-only file systemCurrent file position is 161
GPL Ghostscript 10.02.0: **** Could not open the file ./lilypond-tmp-6010361.pdf .
GPL Ghostscript 10.02.0: Unrecoverable error, exit code 1
warning: `(gs -dNODISPLAY -dNOSAFER -dNOPAUSE -dBATCH -dAutoRotatePages=/None -dPrinted=false /var/folders/71/qfb57y415rq_n65h0720_38w0000gn/T//lilypond-tmp-6950945)' failed (256)

/opt/homebrew/Cellar/lilypond/2.24.2/share/lilypond/2.24.2/ly/init.ly:65:2: error: Guile signaled an error for the expression beginning here
#
 (let ((book-handler (if (defined? 'default-toplevel-book-handler)
/opt/homebrew/Cellar/lilypond/2.24.2/share/lilypond/2.24.2/scm/lily/lily.scm
In ice-9/boot-9.scm:
  1752:10 16 (with-exception-handler _ _ #:unwind? _ # _)
In unknown file:
          15 (apply-smob/0 #<thunk 1058fd2a0>)
In /private/tmp/lilypond-20230812-15627-1qxac7x/lilypond-2.24.2/out/share/lilypond/current/scm/lily/lily.scm:
   873:16 14 (lilypond-main _)
    902:4 13 (lilypond-all ("/Users/mikemccormick/Desktop/main.ly"))
In srfi/srfi-1.scm:
    634:9 12 (for-each #<procedure 105d5e330 at /private/tmp/lilypo…> …)
In /private/tmp/lilypond-20230812-15627-1qxac7x/lilypond-2.24.2/out/share/lilypond/current/scm/lily/lily.scm:
    912:9 11 (_ "/Users/mikemccormick/Desktop/main.ly")
In ice-9/boot-9.scm:
  1747:15 10 (with-exception-handler #<procedure 105d5e2d0 at ice-9…> …)
In unknown file:
           9 (ly:parse-file "/Users/mikemccormick/Desktop/main.ly")
In ice-9/boot-9.scm:
  1752:10  8 (with-exception-handler _ _ #:unwind? _ # _)
In unknown file:
           7 (apply-smob/0 #<thunk 1064b2d20>)
           6 (ly:book-process #<Book> #< Output_def> #< Output_def> #)
In /private/tmp/lilypond-20230812-15627-1qxac7x/lilypond-2.24.2/out/share/lilypond/current/scm/lily/backend-library.scm:
    319:4  5 (postprocess-output #< Output_def> #<directory (lily f…> …)
In srfi/srfi-1.scm:
    634:9  4 (for-each #<procedure 105f55700 at /private/tmp/lilypo…> …)
In /private/tmp/lilypond-20230812-15627-1qxac7x/lilypond-2.24.2/out/share/lilypond/current/scm/lily/backend-library.scm:
    139:4  3 (postscript->pdf 595.2755905511812 841.8897637795277 "…" …)
     57:4  2 (ly:gs-cli _ "mark /OutputFile (./lilypond-tmp-6010361.…")
In ice-9/boot-9.scm:
  1685:16  1 (raise-exception _ #:continuable? _)
In unknown file:
           0 (apply-smob/1 #<exception-handler 1064b2c40> #<&compoun…>)
Throw to key `ly-file-failed' with args `()'.
}
```

**Comment by martineausimon** [comment]
Thank you for sharing this information. Unfortunately, I may not be able to help you : I think the issue might be related to a filesystem permission, possibly with Homebrew, but I'm not familiar with macOS... Please could you share this issue on the [Lilypond forum](https://lists.gnu.org/mailman/listinfo/lilypond-user) ?

**Comment by mccrmck** [comment]
Ah, sorry I disappeared - thanks for the replies!

@jeanas I installed Lilypond via HomeBrew and perhaps I should also mention I've been using nvim-qt?

Installing the binaries (2.24.2) from the link you provided and running nvim from the terminal seemed to work! Could nvim-qt be interfering somehow?

**Comment by mccrmck** [comment]
Updated lilypond to 2.24.3 and no longer have an issue compiling! Thanks to @martineausimon and @jeanas for your patience and suggestions!
