### ISSUE TITLE
Syntax highlighting does not work with LunarVim

### ISSUE THREAD

**Issue by dabrowskiw** [martineausimon/nvim-lilypond-suite#30]
Hello,

using LunarVim, syntax highlighting does not work. The plugin itself loads, the syntax of the file is recognized as "lilypond", the commands work - only the syntax highlighting does not.

This is my minimal config.lua:
```lua
lvim.plugins = {
  {
    "martineausimon/nvim-lilypond-suite",
    depencencies = "MunifTanjim/nui.nvim",
    config = function()
      require('nvls').setup()
    end
  }
}
```

I am using `lvim.plugins` as per the LunarVim documentation, if I directly use `require("lazy").setup()`, LunarVim breaks.

I thought this was related to #14 but given that it still does not work even if the plugin is the only entry in the config file, that does not seem to be the case.

Any ideas what I may be doing wrong?

**Comment by martineausimon** [comment]
Hello,

Sorry for this issue !

I don't use LunarVim, but I've just try a minimal config, adding this lines in `~/.config/nvim/lua/plugins/nvim-lilypond-suite.lua` works for me :

```lua
return {
  'martineausimon/nvim-lilypond-suite',
  config = function()
    require('nvls').setup()
  end
}
```

(note that `MunifTanjim/nui.nvim` is not required anymore)

![2024-01-24-203823_470x214_scrot](https://github.com/martineausimon/nvim-lilypond-suite/assets/89019438/b229baf5-6559-4d35-80b8-06b3d792c078)

Maybe with your config plugins are auto lazy loaded ? Can you try this 2 options ?

```lua
return {
  'martineausimon/nvim-lilypond-suite',
  ft = { "lilypond", "tex", "texinfo" }, -- maybe the best option ?
  --lazy = false, -- if it doesn't works, try this option
  config = function()
    require('nvls').setup()
  end
}
```

**Comment by martineausimon** [comment]
Sorry I confused lunarvim and lazyvim. I have to do another test, but the idea of ​​deactivating lazy loading remains the one that seems to me to be checked first.

**Comment by dabrowskiw** [comment]
Hello,

first of all there is absolutely no need to apoligize - you are creating and sharing a super useful and cool plugin, and on top of that giving out helpful tips, this is awesome!

And your first suggestion worked perfectly - I just added the option `ft = { "lilypond", "tex", "texinfo" }`, and it works like a charm now :)

Again, thanks a lot for your awesome work and patience!
